plugins {
    // No separate org.jetbrains.kotlin.android plugin: AGP 9 has built-in Kotlin support and
    // registers the `kotlin` extension itself. Applying the standalone plugin fails with
    // "Cannot add extension with name 'kotlin'".
    alias(libs.plugins.android.application)
    // Phase 4: consumes the profile the :baselineprofile module generates and packages it (via
    // ProfileInstaller) into the release APK's assets/dexopt.
    alias(libs.plugins.androidx.baselineprofile)
}

android {
    namespace = "com.bhashabridge.app"
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    defaultConfig {
        applicationId = "com.bhashabridge.app"
        minSdk = 24
        targetSdk = 36
        versionCode = 1
        versionName = "1.0"

        // NOT carried from v3.4.1: multiDexEnabled / androidx.multidex. minSdk is 24, and
        // ART has had native multidex since 21 — AGP warns the library is unnecessary.
        // v3.4.1 carried it as legacy baggage.

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
            // Baseline Profiles must be generated from a non-debuggable, release-like build. The
            // generator (and the benchmark measure pass) install that build on-device, so it must be
            // signed. Until the owner provides the real release key (never committed — see
            // THIRD_PARTY_NOTICES / project rules), sign release with the SDK debug key so profile
            // generation works. The owner replaces this for a store build; it does not affect debug.
            signingConfig = signingConfigs.getByName("debug")
        }
    }

    // BuildConfig is not generated by default since AGP 8. logDebug() compiles itself out of
    // release builds via BuildConfig.DEBUG, so this is load-bearing, not boilerplate.
    buildFeatures {
        buildConfig = true
    }

    testOptions {
        unitTests {
            // `android.util.Log` is not mocked in JVM unit tests and throws by default. `Metrics`
            // logs a warning through it when a counter is recorded with no active run on the calling
            // thread — which is exactly what a decoder unit test does, since there is no MtEngine
            // around it to have called begin().
            //
            // Returning defaults instead of throwing keeps `DecoderTest` what it claims to be: the
            // decode algorithms proven with no ONNX, no model and no Android. The alternative was to
            // keep instrumentation out of the decode loop entirely, which would leave the cap-hit
            // rate unmeasurable on a real corpus — and an unmeasurable cap is how the truncation
            // defect survived twice.
            isReturnDefaultValues = true
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlin {
        compilerOptions {
            jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17)
        }
    }

    // Carried from v3.4.1. ONNX Runtime and Vosk each ship their own copies of some
    // .so files; without pickFirsts the merge fails on duplicate native libs.
    packaging {
        resources {
            excludes += setOf(
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE.txt",
                "META-INF/LICENSE",
                "META-INF/NOTICE",
                "META-INF/*.kotlin_module",
                "META-INF/DEPENDENCIES",
            )
        }
        jniLibs {
            pickFirsts += setOf(
                "**/libonnxruntime.so",
                "**/libonnxruntime4j_jni.so",
                "**/libvosk.so",
                "**/libjnidispatch.so",
            )
        }
    }

    // Carried from v3.4.1 (aaptOptions -> androidResources in AGP 9).
    androidResources {
        // NOT `json`. The vocabularies ship DEFLATE-compressed (3.39 MB → 1.19 MB) and storing them
        // uncompressed looked like free speed on the tokenizer load. Measured on the SM-M315F, three
        // fresh processes each: 2,605 ms uncompressed against 2,622 ms compressed — no effect. The
        // cost is the parser, not the inflate (§3.29). Left compressed; the 2.6 MB is not worth an
        // unmeasurable change.
        //
        // NOT `bin` either, since Q23 (§3.54). This read `onnx, bin, pb`, and the reason given was
        // that ONNX Runtime mmaps model files from disk, which a compressed asset cannot do. That was
        // true when ORT loaded out of the APK, and stopped being true at Phase 2B:
        // `OnnxModels.extractAsset` copies every asset into filesDir and ORT loads from *there*, so
        // compression costs one inflate during the first-launch extraction and nothing after it. The
        // weight blobs are ~78% compressible, measured exactly — 506.5 MB stored against 397.4 MB
        // deflated — so storing them was costing 109 MB of every download.
        //
        // `onnx` stays stored on purpose. Those are the six graph files, ~9 MB in total since Phase 13
        // moved the weights out of them, and `AssetManager.openFd` — which the cache stamp reads —
        // works only on stored entries. Keeping them stored keeps that path exact for nothing.
        noCompress += setOf("onnx", "pb")
    }

    // Carried from v3.4.1. Universal APK disabled: a single APK carrying both ABIs plus
    // ~636 MB of models is not installable on the target device.
    splits {
        abi {
            isEnable = true
            reset()
            include("arm64-v8a", "armeabi-v7a")
            isUniversalApk = false
        }
    }
}

dependencies {
    // --- ML stack: versions pinned to v3.4.1's proven set ---
    implementation(libs.onnxruntime.android)
    implementation(libs.vosk.android)
    implementation(libs.kotlinx.coroutines.android)

    // --- AndroidX / Material ---
    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.activity.ktx)
    implementation(libs.androidx.constraintlayout)
    implementation(libs.androidx.drawerlayout)
    implementation(libs.material)

    // --- Lifecycle: required by the Phase 6 ViewModel + process-scoped engine ownership ---
    // runtime-ktx supplies lifecycleScope / repeatOnLifecycle, how the Phase 9 UI collects state.
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.lifecycle.process)

    // --- Phase 4: applies the generated Baseline Profile at install so the hot startup path is
    // AOT-compiled from first launch. Runtime-only; does not touch inference. ---
    implementation(libs.androidx.profileinstaller)
    // Wires generateReleaseBaselineProfile to the :baselineprofile module's on-device journey. Without
    // this the consumer plugin has nothing to collect and emits only library rules.
    baselineProfile(project(":baselineprofile"))

    // --- Test ---
    testImplementation(libs.junit)
    androidTestImplementation(libs.androidx.espresso.core)
    androidTestImplementation(libs.androidx.junit)
}
